# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: 'Default'
  demands:
    - Agent.Version -gt 2.163.1
variables:
  buildConfiguration: 'Release'

steps:
  - script: echo "Pipeline exécuté avec succès."